<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AIAnalysis.Application\AIAnalysis.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Azure.AI.OpenAI" Version="2.9.0-beta.1" />
      <PackageReference Include="MassTransit" Version="8.5.10" />
      <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.5.10" />
      <PackageReference Include="MassTransit.Azure.ServiceBus.Core" Version="8.5.10" />
      <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.10" />
      <PackageReference Include="MediatR" Version="14.2.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
      <PackageReference Include="Microsoft.SemanticKernel" Version="1.78.0" />
      <PackageReference Include="Microsoft.SemanticKernel.Connectors.Postgres" Version="1.51.0-preview" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
      <PackageReference Include="Pgvector.EntityFrameworkCore" Version="0.3.0" />
    </ItemGroup>

</Project>
