<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
      <UserSecretsId>53597fc5-1b17-4ddb-8195-f83bdb65c908</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.23" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.18">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AIAnalysis.Application\AIAnalysis.Application.csproj" />
      <ProjectReference Include="..\AIAnalysis.Infrastructure\AIAnalysis.Infrastructure.csproj" />
    </ItemGroup>

</Project>
